language: rust
rust:
    - stable
    - beta
    - nightly
cache: cargo
before_script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo install rustfmt-nightly --force) fi
script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo fmt --all -- --write-mode=diff) fi
  - cargo test --verbose --all
notifications:
  email: false
